// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Trd_PlaceOrder/Trd_PlaceOrder.proto

package Trd_PlaceOrder

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import Common "lwq/limgo/futupb/Common"
import Trd_Common "limgo/futupb/Trd_Common"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type C2S struct {
	PacketID  *Common.PacketID      `protobuf:"bytes,1,req,name=packetID" json:"packetID,omitempty"`
	Header    *Trd_Common.TrdHeader `protobuf:"bytes,2,req,name=header" json:"header,omitempty"`
	TrdSide   *int32                `protobuf:"varint,3,req,name=trdSide" json:"trdSide,omitempty"`
	OrderType *int32                `protobuf:"varint,4,req,name=orderType" json:"orderType,omitempty"`
	Code      *string               `protobuf:"bytes,5,req,name=code" json:"code,omitempty"`
	Qty       *float64              `protobuf:"fixed64,6,req,name=qty" json:"qty,omitempty"`
	Price     *float64              `protobuf:"fixed64,7,opt,name=price" json:"price,omitempty"`
	// 以下为调整价格使用，目前仅对港、A股有效，因为港股有价位，A股2位精度，美股不需要
	AdjustPrice          *bool    `protobuf:"varint,8,opt,name=adjustPrice" json:"adjustPrice,omitempty"`
	AdjustSideAndLimit   *float64 `protobuf:"fixed64,9,opt,name=adjustSideAndLimit" json:"adjustSideAndLimit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2S) Reset()         { *m = C2S{} }
func (m *C2S) String() string { return proto.CompactTextString(m) }
func (*C2S) ProtoMessage()    {}
func (*C2S) Descriptor() ([]byte, []int) {
	return fileDescriptor_Trd_PlaceOrder_5905b1b2fa780799, []int{0}
}
func (m *C2S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2S.Unmarshal(m, b)
}
func (m *C2S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2S.Marshal(b, m, deterministic)
}
func (dst *C2S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2S.Merge(dst, src)
}
func (m *C2S) XXX_Size() int {
	return xxx_messageInfo_C2S.Size(m)
}
func (m *C2S) XXX_DiscardUnknown() {
	xxx_messageInfo_C2S.DiscardUnknown(m)
}

var xxx_messageInfo_C2S proto.InternalMessageInfo

func (m *C2S) GetPacketID() *Common.PacketID {
	if m != nil {
		return m.PacketID
	}
	return nil
}

func (m *C2S) GetHeader() *Trd_Common.TrdHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *C2S) GetTrdSide() int32 {
	if m != nil && m.TrdSide != nil {
		return *m.TrdSide
	}
	return 0
}

func (m *C2S) GetOrderType() int32 {
	if m != nil && m.OrderType != nil {
		return *m.OrderType
	}
	return 0
}

func (m *C2S) GetCode() string {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return ""
}

func (m *C2S) GetQty() float64 {
	if m != nil && m.Qty != nil {
		return *m.Qty
	}
	return 0
}

func (m *C2S) GetPrice() float64 {
	if m != nil && m.Price != nil {
		return *m.Price
	}
	return 0
}

func (m *C2S) GetAdjustPrice() bool {
	if m != nil && m.AdjustPrice != nil {
		return *m.AdjustPrice
	}
	return false
}

func (m *C2S) GetAdjustSideAndLimit() float64 {
	if m != nil && m.AdjustSideAndLimit != nil {
		return *m.AdjustSideAndLimit
	}
	return 0
}

type S2C struct {
	Header               *Trd_Common.TrdHeader `protobuf:"bytes,1,req,name=header" json:"header,omitempty"`
	OrderID              *uint64               `protobuf:"varint,2,opt,name=orderID" json:"orderID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *S2C) Reset()         { *m = S2C{} }
func (m *S2C) String() string { return proto.CompactTextString(m) }
func (*S2C) ProtoMessage()    {}
func (*S2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_Trd_PlaceOrder_5905b1b2fa780799, []int{1}
}
func (m *S2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2C.Unmarshal(m, b)
}
func (m *S2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2C.Marshal(b, m, deterministic)
}
func (dst *S2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2C.Merge(dst, src)
}
func (m *S2C) XXX_Size() int {
	return xxx_messageInfo_S2C.Size(m)
}
func (m *S2C) XXX_DiscardUnknown() {
	xxx_messageInfo_S2C.DiscardUnknown(m)
}

var xxx_messageInfo_S2C proto.InternalMessageInfo

func (m *S2C) GetHeader() *Trd_Common.TrdHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *S2C) GetOrderID() uint64 {
	if m != nil && m.OrderID != nil {
		return *m.OrderID
	}
	return 0
}

type Request struct {
	C2S                  *C2S     `protobuf:"bytes,1,req,name=c2s" json:"c2s,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_Trd_PlaceOrder_5905b1b2fa780799, []int{2}
}
func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (dst *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(dst, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetC2S() *C2S {
	if m != nil {
		return m.C2S
	}
	return nil
}

type Response struct {
	// 以下3个字段每条协议都有，注释说明在InitConnect.proto中
	RetType              *int32   `protobuf:"varint,1,req,name=retType,def=-400" json:"retType,omitempty"`
	RetMsg               *string  `protobuf:"bytes,2,opt,name=retMsg" json:"retMsg,omitempty"`
	ErrCode              *int32   `protobuf:"varint,3,opt,name=errCode" json:"errCode,omitempty"`
	S2C                  *S2C     `protobuf:"bytes,4,opt,name=s2c" json:"s2c,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_Trd_PlaceOrder_5905b1b2fa780799, []int{3}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

const Default_Response_RetType int32 = -400

func (m *Response) GetRetType() int32 {
	if m != nil && m.RetType != nil {
		return *m.RetType
	}
	return Default_Response_RetType
}

func (m *Response) GetRetMsg() string {
	if m != nil && m.RetMsg != nil {
		return *m.RetMsg
	}
	return ""
}

func (m *Response) GetErrCode() int32 {
	if m != nil && m.ErrCode != nil {
		return *m.ErrCode
	}
	return 0
}

func (m *Response) GetS2C() *S2C {
	if m != nil {
		return m.S2C
	}
	return nil
}

func init() {
	proto.RegisterType((*C2S)(nil), "Trd_PlaceOrder.C2S")
	proto.RegisterType((*S2C)(nil), "Trd_PlaceOrder.S2C")
	proto.RegisterType((*Request)(nil), "Trd_PlaceOrder.Request")
	proto.RegisterType((*Response)(nil), "Trd_PlaceOrder.Response")
}

func init() {
	proto.RegisterFile("Trd_PlaceOrder/Trd_PlaceOrder.proto", fileDescriptor_Trd_PlaceOrder_5905b1b2fa780799)
}

var fileDescriptor_Trd_PlaceOrder_5905b1b2fa780799 = []byte{
	// 378 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x51, 0xcb, 0xae, 0xd3, 0x30,
	0x10, 0x95, 0xf3, 0x68, 0x92, 0xb9, 0x12, 0xba, 0xf2, 0x05, 0x64, 0x15, 0x84, 0xac, 0x20, 0xa4,
	0x2c, 0x68, 0x5a, 0x45, 0xac, 0xd8, 0xa1, 0x74, 0x41, 0x25, 0x1e, 0x95, 0xd3, 0x3d, 0x8a, 0xe2,
	0x11, 0x04, 0x68, 0x9d, 0x3a, 0xee, 0xa2, 0x6b, 0x7e, 0x86, 0xcf, 0x44, 0x76, 0x52, 0xda, 0xa2,
	0x2e, 0x58, 0x79, 0xce, 0xc3, 0xe3, 0x33, 0x1e, 0x78, 0xb9, 0xd1, 0xf2, 0xcb, 0xfa, 0x67, 0xdd,
	0xe0, 0x67, 0x2d, 0x51, 0xcf, 0xaf, 0x61, 0xde, 0x69, 0x65, 0x14, 0x7d, 0x74, 0xcd, 0x4e, 0x1f,
	0x4a, 0xb5, 0xdd, 0xaa, 0xdd, 0x7c, 0x38, 0x06, 0xd3, 0xf4, 0x99, 0x35, 0x8d, 0xc2, 0xb9, 0x1c,
	0xc4, 0xf4, 0xb7, 0x07, 0x7e, 0x59, 0x54, 0xf4, 0x35, 0xc4, 0x5d, 0xdd, 0xfc, 0x40, 0xb3, 0x5a,
	0x32, 0xc2, 0xbd, 0xec, 0xae, 0xb8, 0xcf, 0x47, 0xe3, 0x7a, 0xe4, 0xc5, 0x5f, 0x07, 0x9d, 0xc1,
	0xe4, 0x1b, 0xd6, 0x12, 0x35, 0xf3, 0x9c, 0xf7, 0x49, 0x7e, 0xd1, 0x78, 0xa3, 0xe5, 0x7b, 0x27,
	0x8a, 0xd1, 0x44, 0x19, 0x44, 0x46, 0xcb, 0xaa, 0x95, 0xc8, 0x7c, 0xee, 0x65, 0xa1, 0x38, 0x41,
	0xfa, 0x1c, 0x12, 0x65, 0x93, 0x6f, 0x8e, 0x1d, 0xb2, 0xc0, 0x69, 0x67, 0x82, 0x52, 0x08, 0x1a,
	0x25, 0x91, 0x85, 0xdc, 0xcb, 0x12, 0xe1, 0x6a, 0x7a, 0x0f, 0xfe, 0xde, 0x1c, 0xd9, 0x84, 0x7b,
	0x19, 0x11, 0xb6, 0xa4, 0x8f, 0x21, 0xec, 0x74, 0xdb, 0x20, 0x8b, 0x38, 0xc9, 0x88, 0x18, 0x00,
	0xe5, 0x70, 0x57, 0xcb, 0xef, 0x87, 0xde, 0xac, 0x9d, 0x16, 0x73, 0x92, 0xc5, 0xe2, 0x92, 0xa2,
	0x39, 0xd0, 0x01, 0xda, 0x24, 0xef, 0x76, 0xf2, 0x43, 0xbb, 0x6d, 0x0d, 0x4b, 0x5c, 0x93, 0x1b,
	0x4a, 0xfa, 0x09, 0xfc, 0xaa, 0x28, 0x2f, 0x66, 0x27, 0xff, 0x39, 0xbb, 0x1b, 0x68, 0xb5, 0x64,
	0x1e, 0x27, 0x59, 0x20, 0x4e, 0x30, 0x5d, 0x40, 0x24, 0x70, 0x7f, 0xc0, 0xde, 0xd0, 0x57, 0xe0,
	0x37, 0x45, 0x3f, 0x36, 0x7c, 0xc8, 0xff, 0xd9, 0x75, 0x59, 0x54, 0xc2, 0xea, 0xe9, 0x2f, 0x02,
	0xb1, 0xc0, 0xbe, 0x53, 0xbb, 0x1e, 0xe9, 0x0b, 0x88, 0x34, 0x1a, 0xf7, 0x71, 0xf6, 0x5e, 0xf8,
	0x36, 0x98, 0xbd, 0x59, 0x2c, 0xc4, 0x89, 0xa4, 0x4f, 0x61, 0xa2, 0xd1, 0x7c, 0xec, 0xbf, 0xba,
	0x77, 0x13, 0x31, 0x22, 0x1b, 0x08, 0xb5, 0x2e, 0x95, 0x5b, 0x06, 0xb1, 0xcb, 0x18, 0xa1, 0x4d,
	0xd1, 0x17, 0x0d, 0x0b, 0x38, 0xb9, 0x95, 0xa2, 0x2a, 0x4a, 0x61, 0xf5, 0x3f, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x57, 0x4c, 0xec, 0xbb, 0x9a, 0x02, 0x00, 0x00,
}
