// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Trd_UpdateOrderFill/Trd_UpdateOrderFill.proto

package Trd_UpdateOrderFill

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "limgo/futupb/Common"
import Trd_Common "limgo/futupb/Trd_Common"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type S2C struct {
	Header               *Trd_Common.TrdHeader `protobuf:"bytes,1,req,name=header" json:"header,omitempty"`
	OrderFill            *Trd_Common.OrderFill `protobuf:"bytes,2,req,name=orderFill" json:"orderFill,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *S2C) Reset()         { *m = S2C{} }
func (m *S2C) String() string { return proto.CompactTextString(m) }
func (*S2C) ProtoMessage()    {}
func (*S2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_Trd_UpdateOrderFill_16312d4e2cbc4a6a, []int{0}
}
func (m *S2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2C.Unmarshal(m, b)
}
func (m *S2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2C.Marshal(b, m, deterministic)
}
func (dst *S2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2C.Merge(dst, src)
}
func (m *S2C) XXX_Size() int {
	return xxx_messageInfo_S2C.Size(m)
}
func (m *S2C) XXX_DiscardUnknown() {
	xxx_messageInfo_S2C.DiscardUnknown(m)
}

var xxx_messageInfo_S2C proto.InternalMessageInfo

func (m *S2C) GetHeader() *Trd_Common.TrdHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *S2C) GetOrderFill() *Trd_Common.OrderFill {
	if m != nil {
		return m.OrderFill
	}
	return nil
}

type Response struct {
	// 以下3个字段每条协议都有，注释说明在InitConnect.proto中
	RetType              *int32   `protobuf:"varint,1,req,name=retType,def=-400" json:"retType,omitempty"`
	RetMsg               *string  `protobuf:"bytes,2,opt,name=retMsg" json:"retMsg,omitempty"`
	ErrCode              *int32   `protobuf:"varint,3,opt,name=errCode" json:"errCode,omitempty"`
	S2C                  *S2C     `protobuf:"bytes,4,opt,name=s2c" json:"s2c,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_Trd_UpdateOrderFill_16312d4e2cbc4a6a, []int{1}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

const Default_Response_RetType int32 = -400

func (m *Response) GetRetType() int32 {
	if m != nil && m.RetType != nil {
		return *m.RetType
	}
	return Default_Response_RetType
}

func (m *Response) GetRetMsg() string {
	if m != nil && m.RetMsg != nil {
		return *m.RetMsg
	}
	return ""
}

func (m *Response) GetErrCode() int32 {
	if m != nil && m.ErrCode != nil {
		return *m.ErrCode
	}
	return 0
}

func (m *Response) GetS2C() *S2C {
	if m != nil {
		return m.S2C
	}
	return nil
}

func init() {
	proto.RegisterType((*S2C)(nil), "Trd_UpdateOrderFill.S2C")
	proto.RegisterType((*Response)(nil), "Trd_UpdateOrderFill.Response")
}

func init() {
	proto.RegisterFile("Trd_UpdateOrderFill/Trd_UpdateOrderFill.proto", fileDescriptor_Trd_UpdateOrderFill_16312d4e2cbc4a6a)
}

var fileDescriptor_Trd_UpdateOrderFill_16312d4e2cbc4a6a = []byte{
	// 233 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x4d, 0x4b, 0x03, 0x31,
	0x10, 0x86, 0xc9, 0x6e, 0x3f, 0xec, 0xf4, 0x96, 0xa2, 0x84, 0x0a, 0x12, 0x7a, 0x0a, 0xc2, 0x6e,
	0x4b, 0xf4, 0xe4, 0x35, 0x20, 0x5e, 0x44, 0x48, 0xd7, 0xb3, 0x14, 0x33, 0x68, 0xa1, 0x6d, 0xc2,
	0x24, 0x17, 0xff, 0x81, 0x3f, 0x5b, 0xba, 0x1f, 0xae, 0xe0, 0x9e, 0x92, 0x79, 0x9f, 0x27, 0xbc,
	0x61, 0xa0, 0xa8, 0xc8, 0xbd, 0xbd, 0x06, 0xb7, 0x4b, 0xf8, 0x42, 0x0e, 0xe9, 0x71, 0x7f, 0x38,
	0xac, 0x07, 0xb2, 0x32, 0x90, 0x4f, 0x9e, 0x2f, 0x06, 0xd0, 0x72, 0x61, 0xfc, 0xf1, 0xe8, 0x4f,
	0xeb, 0xe6, 0x68, 0xcc, 0xe5, 0xf5, 0xd9, 0x6c, 0x41, 0x7f, 0x6d, 0xe0, 0x6a, 0x0f, 0xf9, 0x56,
	0x1b, 0x5e, 0xc0, 0xe4, 0x13, 0x77, 0x0e, 0x49, 0x30, 0x99, 0xa9, 0xb9, 0xbe, 0x2c, 0xff, 0x98,
	0x15, 0xb9, 0xa7, 0x1a, 0xda, 0x56, 0xe2, 0x77, 0x30, 0xf3, 0x5d, 0xa9, 0xc8, 0xfe, 0xbf, 0xf8,
	0xfd, 0x91, 0xed, 0xbd, 0xd5, 0x37, 0x83, 0x0b, 0x8b, 0x31, 0xf8, 0x53, 0x44, 0x7e, 0x03, 0x53,
	0xc2, 0x54, 0x7d, 0x05, 0xac, 0x1b, 0xc7, 0x0f, 0xa3, 0xe2, 0x7e, 0xb3, 0xb1, 0x5d, 0xc8, 0xaf,
	0x60, 0x42, 0x98, 0x9e, 0xe3, 0x87, 0xc8, 0x24, 0x53, 0x33, 0xdb, 0x4e, 0x5c, 0xc0, 0x14, 0x89,
	0x8c, 0x77, 0x28, 0x72, 0xc9, 0xd4, 0xd8, 0x76, 0x23, 0xbf, 0x85, 0x3c, 0xea, 0x77, 0x31, 0x92,
	0x4c, 0xcd, 0xb5, 0x28, 0x87, 0x36, 0xb7, 0xd5, 0xc6, 0x9e, 0xa5, 0x9f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x1a, 0x50, 0xc7, 0x6d, 0x6c, 0x01, 0x00, 0x00,
}
