// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Qot_GetBroker/Qot_GetBroker.proto

package Qot_GetBroker

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "limgo/futupb/Common"
import Qot_Common "limgo/futupb/Qot_Common"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type C2S struct {
	Security             *Qot_Common.Security `protobuf:"bytes,1,req,name=security" json:"security,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *C2S) Reset()         { *m = C2S{} }
func (m *C2S) String() string { return proto.CompactTextString(m) }
func (*C2S) ProtoMessage()    {}
func (*C2S) Descriptor() ([]byte, []int) {
	return fileDescriptor_Qot_GetBroker_c0aff2a4cf99549a, []int{0}
}
func (m *C2S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2S.Unmarshal(m, b)
}
func (m *C2S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2S.Marshal(b, m, deterministic)
}
func (dst *C2S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2S.Merge(dst, src)
}
func (m *C2S) XXX_Size() int {
	return xxx_messageInfo_C2S.Size(m)
}
func (m *C2S) XXX_DiscardUnknown() {
	xxx_messageInfo_C2S.DiscardUnknown(m)
}

var xxx_messageInfo_C2S proto.InternalMessageInfo

func (m *C2S) GetSecurity() *Qot_Common.Security {
	if m != nil {
		return m.Security
	}
	return nil
}

type S2C struct {
	Security             *Qot_Common.Security `protobuf:"bytes,1,req,name=security" json:"security,omitempty"`
	BrokerAskList        []*Qot_Common.Broker `protobuf:"bytes,2,rep,name=brokerAskList" json:"brokerAskList,omitempty"`
	BrokerBidList        []*Qot_Common.Broker `protobuf:"bytes,3,rep,name=brokerBidList" json:"brokerBidList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *S2C) Reset()         { *m = S2C{} }
func (m *S2C) String() string { return proto.CompactTextString(m) }
func (*S2C) ProtoMessage()    {}
func (*S2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_Qot_GetBroker_c0aff2a4cf99549a, []int{1}
}
func (m *S2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2C.Unmarshal(m, b)
}
func (m *S2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2C.Marshal(b, m, deterministic)
}
func (dst *S2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2C.Merge(dst, src)
}
func (m *S2C) XXX_Size() int {
	return xxx_messageInfo_S2C.Size(m)
}
func (m *S2C) XXX_DiscardUnknown() {
	xxx_messageInfo_S2C.DiscardUnknown(m)
}

var xxx_messageInfo_S2C proto.InternalMessageInfo

func (m *S2C) GetSecurity() *Qot_Common.Security {
	if m != nil {
		return m.Security
	}
	return nil
}

func (m *S2C) GetBrokerAskList() []*Qot_Common.Broker {
	if m != nil {
		return m.BrokerAskList
	}
	return nil
}

func (m *S2C) GetBrokerBidList() []*Qot_Common.Broker {
	if m != nil {
		return m.BrokerBidList
	}
	return nil
}

type Request struct {
	C2S                  *C2S     `protobuf:"bytes,1,req,name=c2s" json:"c2s,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_Qot_GetBroker_c0aff2a4cf99549a, []int{2}
}
func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (dst *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(dst, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetC2S() *C2S {
	if m != nil {
		return m.C2S
	}
	return nil
}

type Response struct {
	RetType              *int32   `protobuf:"varint,1,req,name=retType,def=-400" json:"retType,omitempty"`
	RetMsg               *string  `protobuf:"bytes,2,opt,name=retMsg" json:"retMsg,omitempty"`
	ErrCode              *int32   `protobuf:"varint,3,opt,name=errCode" json:"errCode,omitempty"`
	S2C                  *S2C     `protobuf:"bytes,4,opt,name=s2c" json:"s2c,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_Qot_GetBroker_c0aff2a4cf99549a, []int{3}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

const Default_Response_RetType int32 = -400

func (m *Response) GetRetType() int32 {
	if m != nil && m.RetType != nil {
		return *m.RetType
	}
	return Default_Response_RetType
}

func (m *Response) GetRetMsg() string {
	if m != nil && m.RetMsg != nil {
		return *m.RetMsg
	}
	return ""
}

func (m *Response) GetErrCode() int32 {
	if m != nil && m.ErrCode != nil {
		return *m.ErrCode
	}
	return 0
}

func (m *Response) GetS2C() *S2C {
	if m != nil {
		return m.S2C
	}
	return nil
}

func init() {
	proto.RegisterType((*C2S)(nil), "Qot_GetBroker.C2S")
	proto.RegisterType((*S2C)(nil), "Qot_GetBroker.S2C")
	proto.RegisterType((*Request)(nil), "Qot_GetBroker.Request")
	proto.RegisterType((*Response)(nil), "Qot_GetBroker.Response")
}

func init() {
	proto.RegisterFile("Qot_GetBroker/Qot_GetBroker.proto", fileDescriptor_Qot_GetBroker_c0aff2a4cf99549a)
}

var fileDescriptor_Qot_GetBroker_c0aff2a4cf99549a = []byte{
	// 278 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x90, 0x41, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0x49, 0xb3, 0xd9, 0xf9, 0xc6, 0x2e, 0x51, 0x24, 0x4c, 0x90, 0x5a, 0x3c, 0xf4, 0xe2,
	0x5a, 0x82, 0xa0, 0x78, 0x73, 0x39, 0x78, 0xd1, 0x83, 0xa9, 0x77, 0xc1, 0xee, 0x21, 0x65, 0x6c,
	0xa9, 0x49, 0x76, 0xd8, 0xd5, 0xaf, 0xe3, 0x97, 0x94, 0xb6, 0x99, 0x5d, 0x41, 0x90, 0x9d, 0x92,
	0xf7, 0xfe, 0xbf, 0x1f, 0xfc, 0x13, 0xb8, 0x7c, 0xd1, 0xee, 0xed, 0x11, 0xdd, 0xdc, 0xe8, 0x25,
	0x9a, 0xb4, 0x37, 0xcd, 0x2a, 0xa3, 0x9d, 0x66, 0x93, 0xde, 0x72, 0x7a, 0x22, 0xf5, 0x6a, 0xa5,
	0xd7, 0x69, 0x7b, 0xb4, 0xcc, 0xf4, 0xbc, 0x66, 0x7c, 0xd0, 0x5d, 0xdb, 0x30, 0xbe, 0x05, 0x2a,
	0x45, 0xce, 0x32, 0x18, 0x59, 0x2c, 0x36, 0xa6, 0x74, 0x5b, 0x4e, 0xa2, 0x20, 0x19, 0x8b, 0xd3,
	0xd9, 0x1e, 0x9b, 0xfb, 0x4c, 0xfd, 0x52, 0xf1, 0x37, 0x01, 0x9a, 0x0b, 0x79, 0xb8, 0xc9, 0xee,
	0x60, 0xf2, 0xde, 0xd4, 0x7d, 0xb0, 0xcb, 0xa7, 0xd2, 0x3a, 0x1e, 0x44, 0x34, 0x19, 0x0b, 0xb6,
	0xaf, 0xb5, 0xef, 0x51, 0x7d, 0xb0, 0x33, 0xe7, 0xe5, 0xa2, 0x31, 0xe9, 0x7f, 0xa6, 0x07, 0xe3,
	0x14, 0x42, 0x85, 0x9f, 0x1b, 0xb4, 0x8e, 0x5d, 0x01, 0x2d, 0x84, 0xf5, 0x5d, 0x5b, 0xb5, 0xfb,
	0x55, 0x29, 0x72, 0x55, 0xc7, 0xf1, 0x17, 0x81, 0x91, 0x42, 0x5b, 0xe9, 0xb5, 0x45, 0x76, 0x01,
	0xa1, 0x41, 0xf7, 0xba, 0xad, 0xb0, 0xd1, 0x86, 0xf7, 0x83, 0xeb, 0x9b, 0x2c, 0x53, 0xbb, 0x25,
	0x3b, 0x83, 0x23, 0x83, 0xee, 0xd9, 0x7e, 0xf0, 0x20, 0x22, 0xc9, 0xb1, 0xf2, 0x13, 0xe3, 0x10,
	0xa2, 0x31, 0x52, 0x2f, 0x90, 0xd3, 0x88, 0x24, 0x43, 0xb5, 0x1b, 0xeb, 0x12, 0x56, 0x14, 0x7c,
	0x10, 0x91, 0x3f, 0x4a, 0xe4, 0x42, 0xaa, 0x3a, 0xfe, 0x09, 0x00, 0x00, 0xff, 0xff, 0x3d, 0xf1,
	0x2f, 0xba, 0x01, 0x02, 0x00, 0x00,
}
