// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Trd_GetOrderFillList/Trd_GetOrderFillList.proto

package Trd_GetOrderFillList

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "limgo/futupb/Common"
import Trd_Common "limgo/futupb/Trd_Common"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type C2S struct {
	Header               *Trd_Common.TrdHeader           `protobuf:"bytes,1,req,name=header" json:"header,omitempty"`
	FilterConditions     *Trd_Common.TrdFilterConditions `protobuf:"bytes,2,opt,name=filterConditions" json:"filterConditions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *C2S) Reset()         { *m = C2S{} }
func (m *C2S) String() string { return proto.CompactTextString(m) }
func (*C2S) ProtoMessage()    {}
func (*C2S) Descriptor() ([]byte, []int) {
	return fileDescriptor_Trd_GetOrderFillList_ee9611b93615638c, []int{0}
}
func (m *C2S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2S.Unmarshal(m, b)
}
func (m *C2S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2S.Marshal(b, m, deterministic)
}
func (dst *C2S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2S.Merge(dst, src)
}
func (m *C2S) XXX_Size() int {
	return xxx_messageInfo_C2S.Size(m)
}
func (m *C2S) XXX_DiscardUnknown() {
	xxx_messageInfo_C2S.DiscardUnknown(m)
}

var xxx_messageInfo_C2S proto.InternalMessageInfo

func (m *C2S) GetHeader() *Trd_Common.TrdHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *C2S) GetFilterConditions() *Trd_Common.TrdFilterConditions {
	if m != nil {
		return m.FilterConditions
	}
	return nil
}

type S2C struct {
	Header               *Trd_Common.TrdHeader   `protobuf:"bytes,1,req,name=header" json:"header,omitempty"`
	OrderFillList        []*Trd_Common.OrderFill `protobuf:"bytes,2,rep,name=orderFillList" json:"orderFillList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *S2C) Reset()         { *m = S2C{} }
func (m *S2C) String() string { return proto.CompactTextString(m) }
func (*S2C) ProtoMessage()    {}
func (*S2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_Trd_GetOrderFillList_ee9611b93615638c, []int{1}
}
func (m *S2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2C.Unmarshal(m, b)
}
func (m *S2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2C.Marshal(b, m, deterministic)
}
func (dst *S2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2C.Merge(dst, src)
}
func (m *S2C) XXX_Size() int {
	return xxx_messageInfo_S2C.Size(m)
}
func (m *S2C) XXX_DiscardUnknown() {
	xxx_messageInfo_S2C.DiscardUnknown(m)
}

var xxx_messageInfo_S2C proto.InternalMessageInfo

func (m *S2C) GetHeader() *Trd_Common.TrdHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *S2C) GetOrderFillList() []*Trd_Common.OrderFill {
	if m != nil {
		return m.OrderFillList
	}
	return nil
}

type Request struct {
	C2S                  *C2S     `protobuf:"bytes,1,req,name=c2s" json:"c2s,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_Trd_GetOrderFillList_ee9611b93615638c, []int{2}
}
func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (dst *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(dst, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetC2S() *C2S {
	if m != nil {
		return m.C2S
	}
	return nil
}

type Response struct {
	// 以下3个字段每条协议都有，注释说明在InitConnect.proto中
	RetType              *int32   `protobuf:"varint,1,req,name=retType,def=-400" json:"retType,omitempty"`
	RetMsg               *string  `protobuf:"bytes,2,opt,name=retMsg" json:"retMsg,omitempty"`
	ErrCode              *int32   `protobuf:"varint,3,opt,name=errCode" json:"errCode,omitempty"`
	S2C                  *S2C     `protobuf:"bytes,4,opt,name=s2c" json:"s2c,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_Trd_GetOrderFillList_ee9611b93615638c, []int{3}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

const Default_Response_RetType int32 = -400

func (m *Response) GetRetType() int32 {
	if m != nil && m.RetType != nil {
		return *m.RetType
	}
	return Default_Response_RetType
}

func (m *Response) GetRetMsg() string {
	if m != nil && m.RetMsg != nil {
		return *m.RetMsg
	}
	return ""
}

func (m *Response) GetErrCode() int32 {
	if m != nil && m.ErrCode != nil {
		return *m.ErrCode
	}
	return 0
}

func (m *Response) GetS2C() *S2C {
	if m != nil {
		return m.S2C
	}
	return nil
}

func init() {
	proto.RegisterType((*C2S)(nil), "Trd_GetOrderFillList.C2S")
	proto.RegisterType((*S2C)(nil), "Trd_GetOrderFillList.S2C")
	proto.RegisterType((*Request)(nil), "Trd_GetOrderFillList.Request")
	proto.RegisterType((*Response)(nil), "Trd_GetOrderFillList.Response")
}

func init() {
	proto.RegisterFile("Trd_GetOrderFillList/Trd_GetOrderFillList.proto", fileDescriptor_Trd_GetOrderFillList_ee9611b93615638c)
}

var fileDescriptor_Trd_GetOrderFillList_ee9611b93615638c = []byte{
	// 296 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x90, 0xcf, 0x4b, 0xfb, 0x30,
	0x18, 0xc6, 0xe9, 0xba, 0xad, 0xdf, 0xef, 0x3b, 0x04, 0x89, 0x3f, 0x88, 0x13, 0xb4, 0xf4, 0x54,
	0x90, 0x75, 0x23, 0x88, 0x07, 0x3d, 0x06, 0xa6, 0xa0, 0x22, 0xa4, 0xbd, 0x8b, 0x2c, 0xaf, 0x5a,
	0xe8, 0x9a, 0x2e, 0x89, 0x07, 0x8f, 0x1e, 0xfd, 0xaf, 0xa5, 0x3f, 0xa6, 0xb3, 0xd6, 0x83, 0xa7,
	0xe4, 0x7d, 0x9f, 0xcf, 0x43, 0x9e, 0x3c, 0x30, 0x4d, 0xb4, 0xbc, 0xbf, 0x44, 0x7b, 0xa7, 0x25,
	0xea, 0x79, 0x9a, 0x65, 0x37, 0xa9, 0xb1, 0x9d, 0xcb, 0xa8, 0xd0, 0xca, 0x2a, 0xb2, 0xdb, 0xa5,
	0x8d, 0x77, 0xb8, 0x5a, 0x2e, 0x55, 0x3e, 0xad, 0x8f, 0x1a, 0x1d, 0x1f, 0x96, 0x68, 0x23, 0x7c,
	0x5d, 0x6b, 0x31, 0x78, 0x73, 0xc0, 0xe5, 0x2c, 0x26, 0x13, 0x18, 0x3e, 0xe3, 0x83, 0x44, 0x4d,
	0x1d, 0xbf, 0x17, 0x8e, 0xd8, 0x5e, 0xb4, 0x81, 0x26, 0x5a, 0x5e, 0x55, 0xa2, 0x68, 0x20, 0x72,
	0x0d, 0xdb, 0x8f, 0x69, 0x66, 0x51, 0x73, 0x95, 0xcb, 0xd4, 0xa6, 0x2a, 0x37, 0xb4, 0xe7, 0x3b,
	0xe1, 0x88, 0x1d, 0xb7, 0x8c, 0xf3, 0x16, 0x26, 0x7e, 0x18, 0x83, 0x15, 0xb8, 0x31, 0xe3, 0x7f,
	0x8d, 0x70, 0x01, 0x5b, 0x6a, 0xf3, 0xf3, 0xb4, 0xe7, 0xbb, 0x6d, 0xd7, 0x67, 0x3b, 0xe2, 0x3b,
	0x1b, 0x9c, 0x81, 0x27, 0x70, 0xf5, 0x82, 0xc6, 0x92, 0x13, 0x70, 0x17, 0xcc, 0x34, 0x6f, 0x1e,
	0x44, 0x9d, 0x9d, 0x73, 0x16, 0x8b, 0x92, 0x0a, 0xde, 0x1d, 0xf8, 0x27, 0xd0, 0x14, 0x2a, 0x37,
	0x48, 0x8e, 0xc0, 0xd3, 0x68, 0x93, 0xd7, 0x02, 0x2b, 0xf7, 0xe0, 0xbc, 0x3f, 0x39, 0x9d, 0xcd,
	0xc4, 0x7a, 0x49, 0xf6, 0x61, 0xa8, 0xd1, 0xde, 0x9a, 0xa7, 0xaa, 0x9a, 0xff, 0xa2, 0x99, 0x08,
	0x05, 0x0f, 0xb5, 0xe6, 0x4a, 0x22, 0x75, 0x7d, 0x27, 0x1c, 0x88, 0xf5, 0x58, 0x66, 0x31, 0x6c,
	0x41, 0xfb, 0x55, 0x93, 0xbf, 0x64, 0x89, 0x19, 0x17, 0x25, 0xf5, 0x11, 0x00, 0x00, 0xff, 0xff,
	0xac, 0xc0, 0x92, 0xe1, 0x34, 0x02, 0x00, 0x00,
}
