// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Qot_UpdateRT/Qot_UpdateRT.proto

package Qot_UpdateRT

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "limgo/futupb/Common"
import Qot_Common "limgo/futupb/Qot_Common"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type S2C struct {
	Security             *Qot_Common.Security    `protobuf:"bytes,1,req,name=security" json:"security,omitempty"`
	RtList               []*Qot_Common.TimeShare `protobuf:"bytes,2,rep,name=rtList" json:"rtList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *S2C) Reset()         { *m = S2C{} }
func (m *S2C) String() string { return proto.CompactTextString(m) }
func (*S2C) ProtoMessage()    {}
func (*S2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_Qot_UpdateRT_ff6c89fb360fd5e5, []int{0}
}
func (m *S2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2C.Unmarshal(m, b)
}
func (m *S2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2C.Marshal(b, m, deterministic)
}
func (dst *S2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2C.Merge(dst, src)
}
func (m *S2C) XXX_Size() int {
	return xxx_messageInfo_S2C.Size(m)
}
func (m *S2C) XXX_DiscardUnknown() {
	xxx_messageInfo_S2C.DiscardUnknown(m)
}

var xxx_messageInfo_S2C proto.InternalMessageInfo

func (m *S2C) GetSecurity() *Qot_Common.Security {
	if m != nil {
		return m.Security
	}
	return nil
}

func (m *S2C) GetRtList() []*Qot_Common.TimeShare {
	if m != nil {
		return m.RtList
	}
	return nil
}

type Response struct {
	RetType              *int32   `protobuf:"varint,1,req,name=retType,def=-400" json:"retType,omitempty"`
	RetMsg               *string  `protobuf:"bytes,2,opt,name=retMsg" json:"retMsg,omitempty"`
	ErrCode              *int32   `protobuf:"varint,3,opt,name=errCode" json:"errCode,omitempty"`
	S2C                  *S2C     `protobuf:"bytes,4,opt,name=s2c" json:"s2c,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_Qot_UpdateRT_ff6c89fb360fd5e5, []int{1}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

const Default_Response_RetType int32 = -400

func (m *Response) GetRetType() int32 {
	if m != nil && m.RetType != nil {
		return *m.RetType
	}
	return Default_Response_RetType
}

func (m *Response) GetRetMsg() string {
	if m != nil && m.RetMsg != nil {
		return *m.RetMsg
	}
	return ""
}

func (m *Response) GetErrCode() int32 {
	if m != nil && m.ErrCode != nil {
		return *m.ErrCode
	}
	return 0
}

func (m *Response) GetS2C() *S2C {
	if m != nil {
		return m.S2C
	}
	return nil
}

func init() {
	proto.RegisterType((*S2C)(nil), "Qot_UpdateRT.S2C")
	proto.RegisterType((*Response)(nil), "Qot_UpdateRT.Response")
}

func init() {
	proto.RegisterFile("Qot_UpdateRT/Qot_UpdateRT.proto", fileDescriptor_Qot_UpdateRT_ff6c89fb360fd5e5)
}

var fileDescriptor_Qot_UpdateRT_ff6c89fb360fd5e5 = []byte{
	// 235 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0x3d, 0x4f, 0xc3, 0x30,
	0x10, 0x86, 0xe5, 0xa4, 0x5f, 0x5c, 0x58, 0x30, 0x1f, 0xb2, 0x8a, 0x04, 0x56, 0x59, 0xbc, 0x34,
	0x8d, 0x2c, 0x26, 0xd6, 0xac, 0x30, 0xe0, 0x84, 0x19, 0x55, 0xed, 0x01, 0x19, 0x52, 0x47, 0xe7,
	0x63, 0xe8, 0xc8, 0x3f, 0x47, 0x25, 0x29, 0x98, 0xe9, 0xee, 0x7d, 0x9f, 0x47, 0x3a, 0xe9, 0xe0,
	0xf6, 0xd9, 0xf3, 0xeb, 0x4b, 0xb7, 0x5d, 0x33, 0xba, 0x7a, 0x15, 0x87, 0xbc, 0x23, 0xcf, 0x5e,
	0x9e, 0xc6, 0xdd, 0xfc, 0xbc, 0xf4, 0x6d, 0xeb, 0x77, 0xab, 0x7e, 0xf4, 0xca, 0xfc, 0xfa, 0xa0,
	0x0c, 0xe0, 0x6f, 0xed, 0xe1, 0xe2, 0x0d, 0xd2, 0xca, 0x96, 0xb2, 0x80, 0x59, 0xc0, 0xcd, 0x27,
	0x35, 0xbc, 0x57, 0x42, 0x27, 0x26, 0xb3, 0x17, 0x79, 0xe4, 0x56, 0x03, 0x73, 0xbf, 0x96, 0x5c,
	0xc2, 0x84, 0xf8, 0xb1, 0x09, 0xac, 0x12, 0x9d, 0x9a, 0xcc, 0x5e, 0xc6, 0x7e, 0xdd, 0xb4, 0x58,
	0x7d, 0xac, 0x09, 0xdd, 0x20, 0x2d, 0xbe, 0x04, 0xcc, 0x1c, 0x86, 0xce, 0xef, 0x02, 0xca, 0x1b,
	0x98, 0x12, 0x72, 0xbd, 0xef, 0xf0, 0xe7, 0xd8, 0xf8, 0x61, 0xb4, 0xbc, 0x2f, 0x0a, 0x77, 0x2c,
	0xe5, 0x15, 0x4c, 0x08, 0xf9, 0x29, 0xbc, 0xab, 0x44, 0x0b, 0x73, 0xe2, 0x86, 0x24, 0x15, 0x4c,
	0x91, 0xa8, 0xf4, 0x5b, 0x54, 0xa9, 0x16, 0x66, 0xec, 0x8e, 0x51, 0xde, 0x41, 0x1a, 0xec, 0x46,
	0x8d, 0xb4, 0x30, 0x99, 0x3d, 0xcb, 0xff, 0x3d, 0xaa, 0xb2, 0xa5, 0x3b, 0xd0, 0xef, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xbb, 0xc1, 0x17, 0xd1, 0x4d, 0x01, 0x00, 0x00,
}
